version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - clippy
  - moeru
  - nixpkgs
  - ortts
  - palc
  - pkgs
  - pname
  - rustc
  - serde
  - utoipa
ignoreWords: []
import: []
