version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - argmax
  - bitnami
  - cangjie
  - clippy
  - coreml
  - cpus
  - cuda
  - directml
  - dtype
  - espeak
  - huggingface
  - jieba
  - kakasi
  - keepdims
  - kokoro
  - libiconv
  - logits
  - moeru
  - ndarray
  - nfkd
  - nixpkgs
  - onnx
  - ortts
  - palc
  - phonemization
  - phonemizer
  - pkgs
  - pname
  - rsplit
  - rustc
  - rustls
  - serde
  - sinc
  - stdenv
  - ureq
  - utoipa
  - webgpu
ignoreWords: []
import: []
